### ISSUE TITLE
Version 8 - WebAPI 2.2 - No route data

### ISSUE THREAD

**Issue by tritzema** [aarondrabeck/zVirtualScenes#2]
Excited to see your continued development on this project. Version 7 returned results at URL:

http://localhost:84/

Now with version 8, get XML document that reads:

<Error><Message>No HTTP resource was found that matches the request URI 'http://localhost:84/'.</Message><MessageDetail>No route data was found for this request.</MessageDetail></Error>

WebAPI 2.2 plugin is enabled and port is set appropriately to "84"

**Comment by aarondrabeck** [comment]
Documentation Here: http://aarondrabeck.github.io/zVirtualScenes/plugin-webapi2.html
